public class ClientAgreement {

	public static void getClientAgreement(String recordId)
	{
	    // //Initialize your page with recordId and call
	    // //Blob data = page.getContentAsPdf
	    ////Replace below URL with your Salesforce instance host
	    //String addr = 'https://c.cs5.visual.force.com/apex/Client_Agreement_AU_EFT_and_VANS?Id='+recordId;
	    //HttpRequest req = new HttpRequest();
	    //req.setEndpoint( addr );
	    //req.setMethod('POST');
	    //req.setHeader('Authorization', 'OAuth ' + userSessionId);
	    //req.setHeader('Content-Type','application/json');

	    //Map<String,String> postBody = new Map<String,String>();
	    //postBody.put('EmailIdCSV',EmailIdCSV);
	    //postBody.put('Subject',Subject);
	    //postBody.put('body',data);
	    //String reqBody = JSON.serialize(postBody);

	    //req.setBody(reqBody);
	    //Http http = new Http();
	    //HttpResponse response = http.send(req);
	}


}